
include "/etc/bind/rndc.key";

controls {
    inet 0.0.0.0 port 953 allow { 127.0.0.1; 172.16.0.0/12; 192.168.0.0/16; 10.0.0.0/8; } keys { "rndc-key"; };
};

include "/etc/bind/named.conf.options";
include "/etc/bind/named.conf.local";
